# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Paul/Documents/VGA/VGA.srcs/sources_1/ip/blk_mem_buffer/blk_mem_buffer.xci
# IP: The module: 'blk_mem_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paul/Documents/VGA/VGA.srcs/sources_1/ip/blk_mem_buffer/blk_mem_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Paul/Documents/VGA/VGA.srcs/sources_1/ip/blk_mem_buffer/blk_mem_buffer.xci
# IP: The module: 'blk_mem_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paul/Documents/VGA/VGA.srcs/sources_1/ip/blk_mem_buffer/blk_mem_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
